bind C-b send-prefix
set -g status-style "bg=#FF9955,fg=black"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
set -s copy-command 'wl-copy'
bind-key -T copy-mode-vi y send -X copy-pipe 'wl-copy'
