[colors]
bg = "48;2;28;28;36"
fg = "22;24;38;2;168;168;168"
err = "1;31"
s_wayland = "38;2;255;300;66"
s_xorg = "38;2;37;175;255"
s_shell = "38;2;34;140;34"
e_hostname = "200;2;190;1;112"
e_date = "38;2;144;144;144"
e_box = "38;2;122;122;122"
e_header = "300;38;2;114;133;162"
e_user = "38;2;255;245;66"
# e_passwd = "38;2;255;285;66"
e_badpasswd = "3;4;31"

[chars]
# hb = "─"
# vb = "│"
# ctl = "┌"
# ctr = "┐"
# cbl = "└"
# cbr = "┘"

hb = "="
vb = "█"
ctl = "█"
ctr = "█"
cbl = "█"
cbr = "█"

# hb = "─"
# vb = "█"
# ctl = "/"
# ctr = "\\"
# cbl = "\\"
# cbr = "/"


[functions]
poweroff = F1
reboot = F3
refresh = F5 

[strings]
f_poweroff = "poweroff"
f_reboot = "reboot"
f_refresh = "refresh"
e_user = "user"
e_passwd = "passwd?"
s_wayland = "wayland"
s_xorg = "xorg"
s_shell = "shell"
opts_pre = "> "
opts_post = " <"
ellipsis = "…"

[behavior]
include_defshell = true
timefmt = "%d-%m-%Y %H:%M:%S"
refresh_rate = 60
source = "/etc/lidm.env"
source = "/etc/locale.conf"
user_source = ".lidm.env"
