[colors]
; background = #111111
background = #282828
background-alt = #373B41
foreground = #d29493
primary = #ffdddd
secondary = #ffffff
alert = #A54242
disabled = #707880

[bar/wow]
; monitor = eDP-1
override-redirect = true
wm-restack = generic
bottom = false


; terminus dimensions
font-0 = Terminus:size=12;2
height = 2.1%
offset-y = 97.9%
width = 25.3%
offset-x = 74.8%

; iosevka dimensions
; font-0 = Iosevka:size=9;3
; height = 2.1%
; offset-y = 97.9%
; width = 25.3%
; offset-x = 74.8%

radius = 0

; dpi = 96
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 4pt
border-size = 1pt
border-color = #111111

padding-left = 0
padding-right = 1
module-margin = 1
separator = \
separator-foreground = ${colors.disabled}


modules-center = brightnessctl battery pulseaudio wlan date mic


enable-ipc = true

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "vol "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = " muted "
label-muted-foreground = ${colors.disabled}
[module/mic]
type = custom/script
interval = 5

exec = ~/.config/polybar/mic-tog.sh
; click-left = pulseaudio-ctl mute-input
; click-right = pavucontrol -t 4 &


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
; label-disconnected = %{F#009999}%ifname%%{F#707880} disconnected
label-disconnected = "%{F#707880} no net "

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:foot nmtui connect &:}%{F#ffdddd}net%{F-} %essid:0:6:%%{A}

[module/date]
type = internal/date
interval = 60

date = "%a, %{F#ffdddd}%d %b - %{F-}%H:%M"

label = %date%
label-foreground = #ffdddd

[settings]
screenchange-reload = true
pseudo-transparency = false

[module/battery]
type = internal/battery

low-at = 30
full-at = 98
battery = BAT0
adapter = ACAD
poll-interval = 5
time-format = %H:%M

format-charging = <label-charging>
; format-charging-prefix = "+BAT "
format-charging-prefix = "+bat "
format-charging-prefix-background = ${colors.background}
format-charging-prefix-foreground = ${colors.primary}
format-charging-background = ${colors.background}
format-charging-foreground = ${colors.foreground}
format-charging-padding = 0
format-discharging = <label-discharging>
format-discharging-background = ${colors.background}
format-discharging-foreground = ${colors.foreground}
format-discharging-padding = 0
; format-discharging-prefix = "-BAT "
format-discharging-prefix = "-bat "
format-discharging-prefix-background = ${colors.background}
format-discharging-prefix-foreground = ${colors.primary}
format-full = <label-full>
format-full-background = ${colors.background}
format-full-foreground = ${colors.foreground}
format-full-padding = 0
label-charging = "%percentage%% %{F#ffdddd}[%{F-} inf %{F#ffdddd}]%{F-}"
label-discharging = "%percentage%% %{F#ffdddd}[%{F-}%time%%{F#ffdddd}]%{F-}"
label-full = "%{F#ffdddd}[%{F-} full charge %{F#ffdddd}]%{F-}"


[module/brightnessctl]
type = custom/script
exec = ~/.config/polybar/brightnessctl.sh
tail = true

; scroll-up = exec brightnessctl-wrapper set +5%
; scroll-down = exec brightnessctl-wrapper set 5%-
interval = 5

format-brightness = <label-brightness>
; format-brightness-prefix = "SCR"
format-brightness-prefix = "scr"
format-brightness-prefix-foreground = $(colors.foreground)
label = "%{F#ffdddd}scr%{F#d29493}%output%"
; label = "%{F#ffdddd}SCR%{F#d29493}%output%"
label-foreground = ${colors.foreground}
